### ISSUE TITLE
all: prefix CMake targets with project name

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial-consortium/descartes_tutorials#2]
See ros-industrial/ros_industrial_issues#8 for the rationale.

`descartes_tutorials` adds a single target ([here](https://github.com/ros-industrial-consortium/descartes_tutorials/blob/46d86e622503b98af2f8005dc340ee0d9e08273d/descartes_tutorial1/CMakeLists.txt#L22)) called `tutorial1` which isn't very uniquely named, so we run a serious risk of clashing with other targets in a populated workspace.

**Comment by Jmeyer1292** [comment]
Do not merge. Investigating issue.

**Comment by gavanderhoorn** [comment]
Closed in #3.
