### ISSUE TITLE
could not connect to action server

### ISSUE THREAD

**Issue by ghost** [ros-industrial-consortium/descartes_tutorials#6]
Hi,
I run the tutorial on kuka_experimental and I got the following error:
[31m[ERROR] [1505239299.379109492]: Could not connect to action server[0m
[31m[ERROR] [1505239299.470796294]: Could not execute trajectory![0m
[33m[ WARN] [1505239299.470913341]: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.[0m

what can cause to the problem?

**Comment by ghost** [comment]
Hey, you need to make sure that actionlib::SimpleActionClient<control_msgs::FollowJointTrajectoryAction> is calling the right trajectory controller (as in you move_group.launch file) as an example, for us "follow_joint_trajectory" worked.

The issue can be closed.
Thanks

**Comment by hariharan382** [comment]
i have made the changes you made. In controllers.yaml i changed the type to followjointtrajectory but still problem persist
